/** \ingroup DWTheRevege */
/*@{*/

/**	
 *	@file	
 *	File: Defs.hpp \n
 *	Framework: Dragonwind II (the revenge) \n
 *	Author: Ignacio Cea Forniés (Community Networks) \n
 *	Creation Date: 24/01/2020 \n
 *	Description: Defines and general includes of Dragonwind II Game
 *	Versions: 1.0 Initial
 */

#ifndef __DRAGONWINDTHEREVENGE_DRAGONWINDGAMEDEFINES__
#define __DRAGONWINDTHEREVENGE_DRAGONWINDGAMEDEFINES__

#include <DragonwindLike/dwdefinitions.hpp>

// A standard configuration parameter to declare the number of lives
#define __DRAGONWINDTHEREVENGE_MAXNUMBEROFLIVESPARAMETER__			"LIVES"
#define __DRAGONWINDTHEREVENGE_DEFAULTMAXNUMBEROFLIVESPARAMETER__	"3"
// same related with showing or not the FPS
#define __DRAGONWINDTHEREVENGE_SHOWFPSPARAMETER__					"FPS"
#define __DRAGONWINDTHEREVENGE_DEFAULTSHOWFPSPARAMETER__			"NO"

// The cityworld
#define __DRAGONWINDTHEREVENGE_CITYWORLDID__						50001
#define __DRAGONWINDTHEREVENGE_CITYWORLDBACKGROUNDMAPID__			__DRAGONWIND_CITYBKMAPID__
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE0ID__					60002
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE0MAPID__				60002
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE1ID__					60003
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE1MAPID__				60003
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE2ID__					60004
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE2MAPID__				60004
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE3ID__					60005
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE3MAPID__				60005
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE4ID__					60006
#define __DRAGONWINDTHEREVENGE_CITYWORLDSCENE4MAPID__				60006

// Sounds
#define __DRAGONWINDTHEREVENGE_OPENDOORSOUNDID__					80000

#endif
  
// End of the file
/*@}*/